/*
	Spacebar: A FOSS re-implementation and extension of the Discord.com backend.
	Copyright (C) 2026 Spacebar and Spacebar Contributors

	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU Affero General Public License as published
	by the Free Software Foundation, either version 3 of the License, or
	(at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU Affero General Public License for more details.

	You should have received a copy of the GNU Affero General Public License
	along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

// server tag badges this instance adds to the client's own. Each is 16x16 pixel art: a grid of palette keys, where a colour
// is fixed or follows the server's badge colours the way the client's badges do: the main (P) or accent (S) colour moved to
// luminance c0 + c1 * luminance(colour), or `def` when the server keeps the badge's own colours. A staff-only one can only
// be put on a server from the admin panel
export type ClanBadgeShade = { ch: "P" | "S"; c0: number; c1: number; def: string };

export interface CustomClanBadge {
    id: number; // well clear of the client's badge ids
    name: string;
    staff_only: boolean;
    pack?: string; // CUSTOM_CLAN_BADGE_PACK when left out
    grid: string[];
    palette: Record<string, string | ClanBadgeShade>;
}

// the client's own shading steps: a dark, base and light tone of the main or accent colour, plus a deeper one for shadows
const TONES = { deep: [0.06, 0.08], dark: [1 / 6, 1 / 6], base: [0.375, 0.25], light: [0.6, 0.25] } as const;
const main = (tone: keyof typeof TONES, def: string): ClanBadgeShade => ({ ch: "P", c0: TONES[tone][0], c1: TONES[tone][1], def });
const accent = (tone: keyof typeof TONES, def: string): ClanBadgeShade => ({ ch: "S", c0: TONES[tone][0], c1: TONES[tone][1], def });

// the pack the instance's badges are grouped under in the client's badge picker and the admin panel, unless a badge names its own
export const CUSTOM_CLAN_BADGE_PACK = "Custom Icon Pack";

// the client's own badges come in a free set and four packs
const DISCORD_CLAN_BADGE_PACKS: [number, number, string][] = [
    [21, 25, "Pets"],
    [26, 30, "Flex"],
    [31, 35, "Plants"],
    [36, 40, "Creepy Crawlies"],
];
export const discordClanBadgePack = (id: number) => DISCORD_CLAN_BADGE_PACKS.find(([first, last]) => id >= first && id <= last)?.[2] ?? "Discord";

export const CUSTOM_CLAN_BADGES: CustomClanBadge[] = [
    {
        id: 10001,
        name: "YOSHI",
        staff_only: false,
        // green follows the main colour, the spikes on his back the accent
        grid: [
            "......KKK.......",
            ".....KWWWK......",
            "....KWWWKWK.....",
            "...RKWWWKWK.....",
            "..RRKWWWWWKKKK..",
            ".RRKGLWWWLGGGGK.",
            "RRKGGGGGGGGGLLGK",
            ".RKGGGGGGGGGGLGK",
            "..KGGGGGGGGGGGGK",
            "..KGGGGGGGGGGGDK",
            "..KWWGGGGGGGGDK.",
            "..KWWWWDDDDDDK..",
            "..KWWWWWKKKKK...",
            "...KWWWWK.......",
            "...KDGGDK.......",
            "...KKKKKK.......",
        ],
        palette: { K: "black", W: "white", G: main("base", "#5BCB45"), L: main("light", "#A6F07A"), D: main("dark", "#2E8B2E"), R: accent("base", "#E83A3A") },
    },
    {
        id: 10002,
        name: "COMPUTER",
        staff_only: false,
        // the casing follows the main colour, the screen the accent
        grid: [
            "................",
            ".KKKKKKKKKKKKKK.",
            ".KPPPPPPPPPPPPK.",
            ".KPSSSSSSSSSSPK.",
            ".KPSLLSSSSSSSPK.",
            ".KPSLSSSSSSSSPK.",
            ".KPSSSSSSSSSSPK.",
            ".KPSSSSSSSSSSPK.",
            ".KPSSSSSSSSSSPK.",
            ".KPPPPPPPPPPPPK.",
            ".KPPPPPPPPPPGPK.",
            ".KKKKKKKKKKKKKK.",
            "......KDDK......",
            "...KKKKDDKKKK...",
            "...KDDDDDDDDK...",
            "...KKKKKKKKKK...",
        ],
        palette: { K: "black", G: "#43E06B", P: main("base", "#B8BDC9"), D: main("dark", "#6D7380"), S: accent("base", "#3D8BFF"), L: accent("light", "#A9D0FF") },
    },
    {
        id: 10003,
        name: "PHONE",
        staff_only: false,
        // the case follows the main colour, the screen the accent
        grid: [
            "....KKKKKKKK....",
            "...KPPPPPPPPK...",
            "...KPPPKKPPPK...",
            "...KPSSSSSSPK...",
            "...KPSLLSSSPK...",
            "...KPSLSSSSPK...",
            "...KPSSSSSSPK...",
            "...KPSSSSSSPK...",
            "...KPSSSSSSPK...",
            "...KPSSSSSSPK...",
            "...KPSSSSSSPK...",
            "...KPSSSSSSPK...",
            "...KPPPPPPPPK...",
            "...KPPPWWPPPK...",
            "...KDPPPPPPDK...",
            "....KKKKKKKK....",
        ],
        palette: { K: "black", W: "white", P: main("base", "#4A4F5C"), D: main("dark", "#2A2D35"), S: accent("base", "#8A5CFF"), L: accent("light", "#D2BCFF") },
    },
    {
        id: 10004,
        name: "CONSOLE",
        staff_only: false,
        // a console controller: the body follows the main colour, the sticks the accent, the face buttons keep their colours
        grid: [
            "................",
            "................",
            "................",
            "..KKKK....KKKK..",
            ".KLLPPKKKKPPPPK.",
            "KLPKPPPPPPPPGPPK",
            "KPKKKPPPPPPMPRPK",
            "KPPKPPPPPPPPBPPK",
            "KPPPPKKPPKKPPPPK",
            "KPPPKSSKKSSKPPPK",
            "KPPPPKKPPKKPPPPK",
            "KPPPKKKKKKKKPPPK",
            ".KDPK......KPDK.",
            "..KK........KK..",
            "................",
            "................",
        ],
        palette: {
            K: "black",
            G: "#3FD18C",
            M: "#F27BC8",
            R: "#F0454B",
            B: "#5A8CFF",
            P: main("base", "#E4E6EB"),
            L: main("light", "#FFFFFF"),
            D: main("dark", "#9AA0AC"),
            S: accent("base", "#3B3F4A"),
        },
    },
    {
        id: 10005,
        name: "FOX",
        staff_only: false,
        // fur follows the main colour, the insides of the ears the accent
        grid: [
            "................",
            ".K............K.",
            ".KK..........KK.",
            ".KSK........KSK.",
            ".KSPK......KPSK.",
            ".KPPPKKKKKKPPPK.",
            "KPPPPPPPPPPPPPPK",
            "KPPKKPPPPPPKKPPK",
            "KWPPPPPPPPPPPPWK",
            "KWWPPPPPPPPPPWWK",
            ".KWWWDPPPPDWWWK.",
            "..KWWWWDDWWWWK..",
            "...KWWWKKWWWK...",
            "....KKWWWWKK....",
            "......KKKK......",
            "................",
        ],
        palette: { K: "black", W: "white", P: main("base", "#F28A2E"), D: main("dark", "#B85A12"), S: accent("dark", "#5C2A0A") },
    },
    {
        id: 10006,
        name: "WOLF",
        staff_only: false,
        // fur follows the main colour, the eyes the accent
        grid: [
            "................",
            ".KK..........KK.",
            ".KLK........KLK.",
            ".KLPK......KPLK.",
            ".KPPPKKKKKKPPPK.",
            ".KPPPPPDDPPPPPK.",
            "KPPDDPPDDPPDDPPK",
            "KPPPSKPPPPKSPPPK",
            "KPPPPPPLLPPPPPPK",
            "KDPPPPLWWLPPPPDK",
            ".KDPPLWWWWLPPDK.",
            "..KDPWWKKWWPDK..",
            "...KDWKKKKWDK...",
            "....KWWKKWWK....",
            ".....KWWWWK.....",
            "......KKKK......",
        ],
        palette: { K: "black", W: "white", P: main("base", "#8C93A3"), L: main("light", "#C9CED9"), D: main("dark", "#555B69"), S: accent("light", "#FFD23F") },
    },
    {
        id: 10007,
        name: "ROBLOX",
        staff_only: false,
        // the tilted block follows the main colour
        grid: [
            "...KKK..........",
            "...KPKKKKK......",
            "..KKLPPPPKKKKK..",
            "..KLPPPPPPPPPKKK",
            "..KPPPPPPPPPPPPK",
            "..KPPPPPPPPPPPKK",
            ".KKPPPPKKKPPPPK.",
            ".KPPPPKKKKPPPPK.",
            ".KPPPPKKKKPPPPK.",
            ".KPPPPKKKPPPPKK.",
            "KKPPPPPPPPPPPK..",
            "KPPPPPPPPPPPPK..",
            "KKKPPPPPPPPPDK..",
            "..KKKKKPPPPDKK..",
            "......KKKKKDK...",
            "..........KKK...",
        ],
        palette: { K: "black", P: main("base", "#E2231A"), L: main("light", "#FF7A70"), D: main("dark", "#9E120C") },
    },
    {
        id: 10008,
        name: "GRASS_BLOCK",
        staff_only: false,
        // a grass topped dirt block: the grass follows the main colour, the dirt the accent
        grid: [
            "......KKKK......",
            "....KKGGGGKK....",
            "..KKGGLGGGGGKK..",
            ".KGGGGLGGGGGGGK.",
            ".KLGGGGGgGGGLGK.",
            "KgggGGGLGGGGhhhK",
            "KgggggGGLGhhhhhK",
            "KDgggggGGhhhhhEK",
            "KDgDdggghhhEEhEK",
            "KDDDDDgghheEEEEK",
            "KDDDDdggEhEeEEEK",
            "KDDDDDDdEEEeEEEK",
            ".KDdDDdDEEEEEEK.",
            "..KKDDDDEEEEKK..",
            "....KKDdEEKK....",
            "......KKKK......",
        ],
        palette: {
            K: "black",
            G: main("base", "#6CC349"),
            L: main("light", "#9BE070"),
            g: main("dark", "#3F8F2B"),
            h: main("deep", "#2A6B1C"),
            D: accent("base", "#9A6B45"),
            d: accent("dark", "#6B4A30"),
            E: accent("dark", "#6B4A30"),
            e: accent("deep", "#47301F"),
        },
    },
    {
        id: 10009,
        name: "HEADPHONES",
        staff_only: false,
        // the headband and cups follow the main colour, the cushions the accent
        grid: [
            "................",
            ".....KKKKKK.....",
            "...KKLLPPPPKK...",
            "..KLPKKKKKKPPK..",
            ".KLKK......KKPK.",
            ".KPK........KPK.",
            "KPK..........KPK",
            "KPKKKK....KKKKPK",
            "KPPSSK....KSSPPK",
            "KPPSSK....KSSPPK",
            "KPPSSK....KSSPPK",
            "KPPSSK....KSSPPK",
            "KDPSSK....KSSPDK",
            ".KKKKK....KKKKK.",
            "................",
            "................",
        ],
        palette: { K: "black", P: main("base", "#3C3F4A"), L: main("light", "#8A8F9E"), D: main("dark", "#22242B"), S: accent("base", "#FF4F8B") },
    },
    {
        id: 10010,
        name: "ROCKET",
        staff_only: false,
        // the body follows the main colour, the nose and fins the accent
        grid: [
            ".......KK.......",
            "......KSSK......",
            ".....KSSSSK.....",
            ".....KPPPPK.....",
            "....KPLPPPPK....",
            "....KLPKKPPK....",
            "....KPKCCKPK....",
            "....KPKCCKPK....",
            "....KPPKKPPK....",
            "....KPPPPPDK....",
            "...KSKPPPDKSK...",
            "..KSSKPPPDKSSK..",
            "..KSSKKKKKKSSK..",
            "..KKK..YY..KKK..",
            "......OYYO......",
            ".......OO.......",
        ],
        palette: {
            K: "black",
            C: "#9FE3FF",
            Y: "#FFD23F",
            O: "#FF7A1A",
            P: main("base", "#DADDE6"),
            L: main("light", "#FFFFFF"),
            D: main("dark", "#8E93A0"),
            S: accent("base", "#E8433A"),
        },
    },
    {
        id: 10011,
        name: "GHOST",
        staff_only: false,
        // the sheet follows the main colour, the pupils the accent
        grid: [
            "................",
            ".....KKKKKK.....",
            "...KKLLPPPPKK...",
            "..KLLPPPPPPPPK..",
            ".KLPPPPPPPPPPPK.",
            ".KPPWWPPPPWWPPK.",
            "KPPWWWWPPWWWWPPK",
            "KPPWWSSPPWWSSPPK",
            "KPPWWSSPPWWSSPPK",
            "KPPPWWPPPPWWPPPK",
            "KPPPPPPPPPPPPPPK",
            "KPPPPPPPPPPPPPPK",
            "KPPPPPPPPPPPPPDK",
            "KPPKKPPPPPPKKPDK",
            "KPK..KPPPPK..KDK",
            "KK....KKKK....KK",
        ],
        palette: { K: "black", W: "white", P: main("base", "#B9A6FF"), L: main("light", "#E6DEFF"), D: main("dark", "#7A63D9"), S: accent("dark", "#2E3BD6") },
    },
    {
        id: 10012,
        name: "PIZZA",
        staff_only: false,
        // the cheese follows the main colour, the pepperoni the accent
        grid: [
            "................",
            ".KKKKKKKKKKKKKK.",
            "KCCCCCCCCCCCCCCK",
            "KDCCCCCCCCCCCCDK",
            ".KDDDDDDDDDDDDK.",
            ".KPLPPPPPPPPPPK.",
            "..KPPSSPPPPLPK..",
            "..KPSSSSPPPPPK..",
            "...KPSSPPPSSK...",
            "...KPPPPPSSSK...",
            "....KPLPPSSK....",
            "....KPSSPPPK....",
            ".....KSSPPK.....",
            "......KPPK......",
            ".......KK.......",
            "................",
        ],
        palette: { K: "black", C: "#E0A060", D: "#A8662E", P: main("base", "#FFC83D"), L: main("light", "#FFF0A8"), S: accent("base", "#D9382C") },
    },
    {
        id: 10013,
        name: "INVADER",
        staff_only: false,
        // a pixel space invader in the main colour
        grid: [
            "................",
            "...K........K...",
            "..KPK......KPK..",
            "...KPK....KPK...",
            "...KPPKKKKPPK...",
            "..KLLPPPPPPPPK..",
            ".KPLKKPPPPKKPPK.",
            ".KPPKKPPPPKKPPK.",
            "KPPPPPPPPPPPPPPK",
            "KPPPPPPPPPPPPPPK",
            "KPKPPPPPPPPPPKPK",
            "KPKPKKKKKKKKPKPK",
            "KPKPK......KPKPK",
            "KKKPPPK..KPPPKKK",
            "...KKKK..KKKK...",
            "................",
        ],
        palette: { K: "black", P: main("base", "#4BE07A"), L: main("light", "#B6FFC9") },
    },
    {
        id: 10014,
        name: "PENGUIN",
        staff_only: false,
        // the feathers follow the main colour, the beak and feet the accent
        grid: [
            "................",
            ".....KKKKKK.....",
            "....KPPPPPPK....",
            "...KPLPPPPPPK...",
            "...KPPWWWWPPK...",
            "...KPWKWWKWPK...",
            "...KPWWSSWWPK...",
            "..KPPPWWWWPPPK..",
            "..KPPWWWWWWPPK..",
            ".KPPPWWWWWWPPPK.",
            "KPKPPWWWWWWPPKPK",
            "KK.KPWWWWWWPK.KK",
            "...KPWWWWWWPK...",
            "...KPPWWWWPPK...",
            "..KSSSKKKKSSSK..",
            "..KKKK....KKKK..",
        ],
        palette: { K: "black", W: "white", P: main("base", "#3A4150"), L: main("light", "#6E7890"), S: accent("base", "#FF9F1C") },
    },
    {
        id: 10015,
        name: "CLYDE",
        staff_only: false,
        // a little robot: the head follows the main colour, the antenna and ears the accent
        grid: [
            ".......KK.......",
            "......KSSK......",
            "......KSSK......",
            ".......KK.......",
            "..KKKKKKKKKKKK..",
            ".KLLPPPPPPPPPPK.",
            ".KLPPPPPPPPPPDK.",
            "KKPPWWWPPWWWPDKK",
            "SKPPWKWPPWKWPDKS",
            "SKPPWWWPPWWWPDKS",
            "KKPPPPPPPPPPPDKK",
            ".KPPKPPPPPPKPDK.",
            ".KPPPKKKKKKPPDK.",
            ".KDPPPPPPPPPPDK.",
            "..KKKKKKKKKKKK..",
            "................",
        ],
        palette: { K: "black", W: "white", P: main("base", "#5865F2"), L: main("light", "#A3ABFF"), D: main("dark", "#3C45B8"), S: accent("base", "#57F287") },
    },
    {
        id: 10016,
        name: "STAR",
        staff_only: false,
        // a star in the main colour
        grid: [
            ".......KK.......",
            "......KPPK......",
            "......KLPK......",
            ".....KPLPPK.....",
            "KKKKKKPLPPKKKKKK",
            "KPPPPPLPPPPPPPPK",
            ".KPPPPPPPPPPPDK.",
            "..KPPPPPPPPPDK..",
            "...KPPPPPPPDK...",
            "...KPPPPPPPDK...",
            "..KPPPPPPPPPDK..",
            "..KPPPPKKPPPDK..",
            ".KPPPKK..KKPDDK.",
            ".KPPK......KPDK.",
            "KPKK........KKDK",
            "KK............KK",
        ],
        palette: { K: "black", P: main("base", "#FFD23F"), L: main("light", "#FFF3A8"), D: main("dark", "#D9A21A") },
    },
    {
        id: 10017,
        name: "MUSIC_NOTE",
        staff_only: false,
        // a pair of beamed notes in the main colour
        grid: [
            "................",
            ".....KKKKKKKKKK.",
            ".....KLLPPPPPPK.",
            ".....KPPPPPPPPK.",
            ".....KPKKKKKKPK.",
            ".....KPK....KPK.",
            ".....KPK....KPK.",
            ".....KPK....KPK.",
            ".....KPK....KPK.",
            "..KKKKPK.KKKKPK.",
            ".KLPPPPKKLPPPPK.",
            ".KPPPPPKKPPPPPK.",
            "..KPPPK..KPPPK..",
            "...KKK....KKK...",
            "................",
            "................",
        ],
        palette: { K: "black", P: main("base", "#C77DFF"), L: main("light", "#EBCCFF") },
    },
    {
        id: 10018,
        name: "MICROPHONE",
        staff_only: false,
        // the mic follows the main colour, its band the accent
        grid: [
            ".....KKKKKK.....",
            "....KLPPPPDK....",
            "....KPDPDPDK....",
            "....KLPPPPDK....",
            "....KPDPDPDK....",
            "..K.KLPPPPDK.K..",
            ".KGKKSSSSSSKKGK.",
            ".KGK.KPPPPK.KGK.",
            ".KGGK.KKKK.KGGK.",
            "..KGGKKKKKKGGK..",
            "...KKGGGGGGKK...",
            "......KGGK......",
            "......KGGK......",
            "...KKKKGGKKKK...",
            "...KGGGGGGGGK...",
            "...KKKKKKKKKK...",
        ],
        palette: { K: "black", G: "#8E93A0", P: main("base", "#C9CED9"), L: main("light", "#FFFFFF"), D: main("dark", "#7D8494"), S: accent("base", "#E8433A") },
    },
    {
        id: 10019,
        name: "CAMERA",
        staff_only: false,
        // the body follows the main colour, the lens the accent
        grid: [
            "................",
            "................",
            "....KKKKK...KKK.",
            "...KDDDDDK..KWK.",
            "KKKKKKKKKKKKKKKK",
            "KPPPPPKKKKPPPPPK",
            "KPPPPKBBBBKPPPPK",
            "KPPPKBSSSSBKPPPK",
            "KPPPKBSASSBKPPPK",
            "KDDDKBSSSSBKDDDK",
            "KPPPKBSSSSBKPPPK",
            "KPPPPKBBBBKPPPPK",
            "KPPPPPKKKKPPPPPK",
            "KDPPPPPPPPPPPPDK",
            "KKKKKKKKKKKKKKKK",
            "................",
        ],
        palette: {
            K: "black",
            W: "white",
            B: "#1E2026",
            P: main("base", "#4A4F5C"),
            D: main("dark", "#2E323B"),
            S: accent("base", "#3D8BFF"),
            A: accent("light", "#A9D0FF"),
        },
    },
    {
        id: 10020,
        name: "TERMINAL",
        staff_only: false,
        // a code window: the title bar follows the main colour, the prompt the accent
        grid: [
            "................",
            "................",
            "................",
            "KKKKKKKKKKKKKKKK",
            "KPRPYPGPPPPPPPPK",
            "KKKKKKKKKKKKKKKK",
            "KBBBBBBBBBBBBBBK",
            "KBSSBBBBBBBBBBBK",
            "KBBSSBBBBBBBBBBK",
            "KBBBSSBBBBBBBBBK",
            "KBBSSBBBBBBBBBBK",
            "KBSSBBSSSSSBBBBK",
            "KBBBBBBBBBBBBBBK",
            "KKKKKKKKKKKKKKKK",
            "................",
            "................",
        ],
        palette: {
            K: "black",
            B: "#1E2026",
            R: "#F0454B",
            Y: "#FFC83D",
            G: "#43E06B",
            P: main("base", "#5865F2"),
            S: accent("light", "#43E06B"),
        },
    },
    {
        id: 10021,
        name: "COFFEE",
        staff_only: false,
        // the mug follows the main colour, the heart on it the accent
        grid: [
            "......E..E......",
            ".....E..E.......",
            ".....E..E.......",
            "......E..E......",
            "..KKKKKKKKKK....",
            "..KBBBBBBBBK....",
            "..KLPPPPPPDKKKK.",
            "..KLPPPPPPDKPPPK",
            "..KLPSPSPPDKKKPK",
            "..KLPSSSPPDKKKPK",
            "..KLPPSPPPDKPPPK",
            "..KLPPPPPPDKKKK.",
            "..KDDDDDDDDK....",
            "...KKKKKKKK.....",
            "................",
            "................",
        ],
        palette: {
            K: "black",
            E: "#C9CED9",
            B: "#6B4A30",
            P: main("base", "#ECEEF2"),
            L: main("light", "#FFFFFF"),
            D: main("dark", "#A7ADBA"),
            S: accent("base", "#F0454B"),
        },
    },
    {
        id: 10022,
        name: "DONUT",
        staff_only: false,
        // the frosting follows the main colour, some of the sprinkles the accent
        grid: [
            "................",
            ".....KKKKKK.....",
            "...KKCCCCCCKK...",
            "..KCCLLYPCCccK..",
            "..KCCSPPPPPPcK..",
            ".KCLLPPKKPPPPcK.",
            ".KLSPPK..KPYccK.",
            "KCLPPK....KPPccK",
            "KccPWK....KPPPcK",
            ".KccPPK..KPPWPK.",
            ".KcPPPPKKPSPPcK.",
            "..KcPPYPPPPccK..",
            "..KccccPSPPccK..",
            "...KKccccccKK...",
            ".....KKKKKK.....",
            "................",
        ],
        palette: {
            K: "black",
            W: "white",
            Y: "#FFD23F",
            C: "#E0A060",
            c: "#B87638",
            P: main("base", "#FF8FC7"),
            L: main("light", "#FFD1EA"),
            S: accent("base", "#3D8BFF"),
        },
    },
    {
        id: 10023,
        name: "ICE_CREAM",
        staff_only: false,
        // the scoop follows the main colour, the cherry the accent
        grid: [
            ".......KK.......",
            "......KSSK......",
            ".....KKSSKK.....",
            "....KLLPPPPK....",
            "...KLPPPPPPPK...",
            "..KLPPPPPPPPDK..",
            "..KPPPPPPPPPDK..",
            ".KPPPPPPPPPPPDK.",
            ".KDPDDPDDPDDPDK.",
            "..KKCcCcCcCcKK..",
            "....KCcCcCcK....",
            "....KcCcCcCK....",
            ".....KCcCcK.....",
            "......KcCK......",
            ".......KK.......",
            "................",
        ],
        palette: {
            K: "black",
            C: "#E0A060",
            c: "#B87638",
            P: main("base", "#FF8FC7"),
            L: main("light", "#FFD1EA"),
            D: main("dark", "#D9579A"),
            S: accent("base", "#E8233A"),
        },
    },
    {
        id: 10024,
        name: "BURGER",
        staff_only: false,
        // the bun follows the main colour, the cheese the accent
        grid: [
            "................",
            ".....KKKKKK.....",
            "...KKPPPPPPKK...",
            "..KPPWPPPPWPPK..",
            ".KPPPPPPWPPPPPK.",
            ".KLPPWPPPPPPWPK.",
            "KPPPPPPPPPPPPPPK",
            "KKKKKKKKKKKKKKKK",
            "KGGGGGGGGGGGGGGK",
            "KSSSSSSSSSSSSSSK",
            "KBSBBBBBBBSBBBBK",
            "KBBBBBBBBBBBBBBK",
            "KKKKKKKKKKKKKKKK",
            "KDPPPPPPPPPPPPDK",
            ".KDDDDDDDDDDDDK.",
            "..KKKKKKKKKKKK..",
        ],
        palette: {
            K: "black",
            W: "#FFF6DC",
            G: "#5DC44A",
            B: "#6B3A1E",
            P: main("base", "#E0A050"),
            L: main("light", "#F5C982"),
            D: main("dark", "#A8662E"),
            S: accent("base", "#FFC83D"),
        },
    },
    {
        id: 10025,
        name: "WATERMELON",
        staff_only: false,
        // the flesh follows the main colour, the rind the accent
        grid: [
            "................",
            "................",
            "................",
            "................",
            "KKKKKKKKKKKKKKKK",
            "KSWPPPPPPPPPPWSK",
            "KSWPPKPPPPKPPWSK",
            "KSWPPPPPKPPPPWSK",
            ".KSWPKPPPPKPWSK.",
            ".KSSWPPPPPPWSSK.",
            "..KSSWWPPWWSSK..",
            "...KKSSWWSSKK...",
            ".....KKKKKK.....",
            "................",
            "................",
            "................",
        ],
        palette: { K: "black", W: "#EAF7D9", P: main("base", "#F2545B"), S: accent("base", "#3FA34D") },
    },
    {
        id: 10026,
        name: "PLANET",
        staff_only: false,
        // the planet follows the main colour, its ring the accent
        grid: [
            "................",
            "................",
            "......KKKK......",
            ".....KLLLPK...KK",
            "....KLLLPPPKKKTT",
            "...KLLLPPKKKTTSS",
            "..KLLLPKKTTTSSKK",
            "..KLLKKTTSSSKK..",
            "..KKKTTSSKKKDK..",
            ".KKTTSSKKPDDDK..",
            "KTTSSKKPPDDDK...",
            "TSSKKPPPDDDK....",
            "SKK..KPDDDK.....",
            "K.....KKKK......",
            "................",
            "................",
        ],
        palette: {
            K: "black",
            P: main("base", "#F2A65A"),
            L: main("light", "#FFD9A8"),
            D: main("dark", "#B8682A"),
            S: accent("base", "#C9B8FF"),
            T: accent("light", "#EDE6FF"),
        },
    },
    {
        id: 10027,
        name: "UFO",
        staff_only: false,
        // the saucer follows the main colour, the dome the accent
        grid: [
            "................",
            "................",
            "................",
            "......KKKK......",
            ".....KAAAAK.....",
            "....KAWAAAAK....",
            "....KAAAAAAK....",
            "..KKKKKKKKKKKK..",
            ".KLPPPPPPPPPPPK.",
            "KPYPPYPPYPPYPPPK",
            "KDDDDDDDDDDDDDDK",
            ".KKKKKKKKKKKKKK.",
            ".....bbbbbb.....",
            "....bbbbbbbb....",
            "...bbbbbbbbbb...",
            "................",
        ],
        palette: {
            K: "black",
            W: "white",
            Y: "#FFD23F",
            b: "#FFF3A0",
            P: main("base", "#B8BDC9"),
            L: main("light", "#E9ECF2"),
            D: main("dark", "#6D7380"),
            A: accent("light", "#9FE3FF"),
        },
    },
    {
        id: 10028,
        name: "DUCK",
        staff_only: false,
        // a rubber duck: the body follows the main colour, the beak the accent
        grid: [
            "................",
            "................",
            ".....KKKK.......",
            "....KLPPPK......",
            "...KPPKPPPK.....",
            ".KKKPPPPPPK.....",
            "KSSSKPPPPPK.....",
            ".KSSKPPPPPK..KK.",
            "..KKPPPPPPPKKPPK",
            "...KPPPPPPPPPPPK",
            "..KPPPPDDDPPPPDK",
            "..KPPPPPDDPPPPDK",
            "..KPPPPPPPPPPDK.",
            "...KDPPPPPPPDK..",
            "....KKKKKKKKK...",
            "................",
        ],
        palette: { K: "black", P: main("base", "#FFD23F"), L: main("light", "#FFF0A8"), D: main("dark", "#D9A21A"), S: accent("base", "#FF7A1A") },
    },
    {
        id: 10029,
        name: "PANDA",
        staff_only: false,
        // the dark patches follow the main colour, the blush the accent
        grid: [
            "................",
            ".KKK........KKK.",
            "KPPPKKKKKKKKPPPK",
            "KPPKWWWWWWWWKPPK",
            ".KKWWWWWWWWWWKK.",
            ".KWWWWWWWWWWWWK.",
            "KWWPPPWWWWPPPWWK",
            "KWPPWPWWWWPWPPWK",
            "KWPPPPWWWWPPPPWK",
            "KWWPPWWWWWWPPWWK",
            "KWWWWWKKKKWWWWWK",
            ".KWWWWWKKWWWWWK.",
            ".KWSWWKWWKWWSWK.",
            "..KWWWWKKWWWWK..",
            "...KKWWWWWWKK...",
            ".....KKKKKK.....",
        ],
        palette: { K: "black", W: "white", P: main("dark", "#2E3440"), S: accent("light", "#FF8FB0") },
    },
    {
        id: 10030,
        name: "OCTOPUS",
        staff_only: false,
        // the octopus follows the main colour, its cheeks the accent
        grid: [
            "................",
            ".....KKKKKK.....",
            "....KLLPPPPK....",
            "...KLPPPPPPPK...",
            "...KPPPPPPPPK...",
            "...KPWKPPWKPK...",
            "...KPWKPPWKPK...",
            "...KSPPPPPPSK...",
            "..KPPPPPPPPPPK..",
            ".KPPPPPPPPPPPPK.",
            "KPPKPPKPPKPPKPPK",
            "KPKKPKKPPKKPKKPK",
            "KPK.KPKPPKPK.KPK",
            ".KPKKPKKKKPKKPK.",
            "..KK.KK..KK.KK..",
            "................",
        ],
        palette: { K: "black", W: "white", P: main("base", "#FF6B8A"), L: main("light", "#FFB8C8"), S: accent("light", "#FFC2D1") },
    },
    {
        id: 10031,
        name: "OWL",
        staff_only: false,
        // the feathers follow the main colour, the eyes the accent
        grid: [
            "................",
            "..KK........KK..",
            "..KPK......KPK..",
            "..KPPKKKKKKPPK..",
            ".KPPPPPPPPPPPPK.",
            ".KPWWWWPPWWWWPK.",
            ".KPWSKWPPWKSWPK.",
            ".KPWSSWPPWSSWPK.",
            ".KPPWWPOOPWWPPK.",
            ".KPPPPPOOPPPPPK.",
            ".KPPLLLLLLLLPPK.",
            ".KPLDLLDLLDLLPK.",
            ".KPLLLLLLLLLLPK.",
            "..KPLDLLDLLDPK..",
            "...KKOKKKKOKK...",
            "................",
        ],
        palette: {
            K: "black",
            W: "white",
            O: "#FF9F1C",
            P: main("base", "#A0703C"),
            L: main("light", "#E8C99A"),
            D: main("dark", "#6B4A30"),
            S: accent("base", "#FFC83D"),
        },
    },
    {
        id: 10032,
        name: "POTION",
        staff_only: false,
        // the potion follows the main colour
        grid: [
            "......KKKK......",
            "......KCCK......",
            ".....KKKKKK.....",
            "......KGGK......",
            "......KGGK......",
            "....KKGGGGKK....",
            "...KGWGGGGGGK...",
            "..KGPPPPPPPPGK..",
            "..KPPLPPPPPPPK..",
            ".KPPPPPPLPPPPPK.",
            ".KPLPPPPPPPPPDK.",
            ".KPPPPPPPPPPPDK.",
            ".KPPPPPPPPPPDDK.",
            "..KPPPPPPPPDDK..",
            "...KKKKKKKKKK...",
            "................",
        ],
        palette: {
            K: "black",
            W: "white",
            C: "#A8662E",
            G: "#DDEBFF",
            P: main("base", "#B65CFF"),
            L: main("light", "#E2B8FF"),
            D: main("dark", "#7A2FC2"),
        },
    },
    {
        id: 10033,
        name: "SHIELD",
        staff_only: false,
        // a quartered shield in the main and accent colours
        grid: [
            ".KKKKKKKKKKKKKK.",
            ".KLPPPPPSSSSSSK.",
            ".KLPPPPPSSSSSSK.",
            ".KPPPPPPSSSSSSK.",
            ".KPPPPPPSSSSSSK.",
            ".KPPPPPPSSSSSSK.",
            ".KPPPPPPSSSSSSK.",
            ".KSSSSSSPPPPPPK.",
            ".KSSSSSSPPPPPPK.",
            ".KSSSSSSPPPPPPK.",
            "..KSSSSSPPPPPK..",
            "..KSSSSSPPPPPK..",
            "...KSSSSPPPPK...",
            "....KSSSPPPK....",
            ".....KKSPKK.....",
            ".......KK.......",
        ],
        palette: { K: "black", P: main("base", "#3D8BFF"), L: main("light", "#A9D0FF"), S: accent("base", "#E8EAF0") },
    },
    {
        id: 10034,
        name: "DICE",
        staff_only: false,
        // the die follows the main colour, its pips the accent
        grid: [
            "................",
            "................",
            "..KKKKKKKKKKKK..",
            ".KLLPPPPPPPPPDK.",
            ".KLSSPPPPPPSSDK.",
            ".KPSSPPPPPPSSDK.",
            ".KPPPPPPPPPPPDK.",
            ".KPPPPPSSPPPPDK.",
            ".KPPPPPSSPPPPDK.",
            ".KPPPPPPPPPPPDK.",
            ".KPSSPPPPPPSSDK.",
            ".KPSSPPPPPPSSDK.",
            ".KPPPPPPPPPPPDK.",
            ".KDDDDDDDDDDDDK.",
            "..KKKKKKKKKKKK..",
            "................",
        ],
        palette: { K: "black", P: main("base", "#F2F3F5"), L: main("light", "#FFFFFF"), D: main("dark", "#B5BAC6"), S: accent("base", "#E8433A") },
    },
    {
        id: 10035,
        name: "BOMB",
        staff_only: false,
        // the bomb follows the main colour, the spark on its fuse the accent
        grid: [
            ".........Y.S....",
            "..........F.Y...",
            "......KKKF......",
            ".....KGGGK......",
            ".....KGGGK......",
            "...KKLLLPPKK....",
            "..KLLLLPPPPPK...",
            "..KLLLPPPPPPK...",
            ".KLLLPPPPPPPPK..",
            ".KLLPPPPPPPPDK..",
            ".KLPPPPPPPPDDK..",
            ".KPPPPPPPPDDDK..",
            "..KPPPPPPDDDK...",
            "..KPPPPPDDDDK...",
            "...KKPPDDDKK....",
            ".....KKKKK......",
        ],
        palette: {
            K: "black",
            G: "#8E93A0",
            F: "#A8662E",
            Y: "#FFD23F",
            P: main("base", "#3A3F4B"),
            L: main("light", "#7D8494"),
            D: main("dark", "#22252C"),
            S: accent("light", "#FF7A1A"),
        },
    },
    {
        id: 10036,
        name: "WINDOWS",
        staff_only: false,
        // the four window panes in perspective, in the main colour
        grid: [
            "......KKKKKKKKKK",
            "......KLLLLLLLLK",
            "KKKKKKKLPPPPPPDK",
            "KLLLLLKLPPPPPPDK",
            "KLPPPDKLPPPPPPDK",
            "KLPPPDKLPPPPPPDK",
            "KLPPPDKLPPPPPPDK",
            "KKKKKKKKKKKKKKKK",
            "KLLLLLKLLLLLLLLK",
            "KLPPPDKLPPPPPPDK",
            "KLPPPDKLPPPPPPDK",
            "KLPPPDKLPPPPPPDK",
            "KDDDDDKLPPPPPPDK",
            "KKKKKKKLPPPPPPDK",
            "......KDDDDDDDDK",
            "......KKKKKKKKKK",
        ],
        palette: { K: "black", P: main("base", "#00A4EF"), L: main("light", "#8AD8FF"), D: main("dark", "#0072B5") },
    },
    {
        id: 10037,
        name: "APPLE",
        staff_only: false,
        // a bitten apple: the fruit follows the main colour, the leaf the accent
        grid: [
            ".........KKK....",
            "........KSSK....",
            ".......KSSK.....",
            ".......KKK......",
            "..KKKKK.KKKKK...",
            ".KLLPPPKPPPPPK..",
            "KLLPPPPPPPPPPK..",
            "KLPPPPPPPPPPK...",
            "KLPPPPPPPPPK....",
            "KPPPPPPPPPPK....",
            "KPPPPPPPPPPPK...",
            "KPPPPPPPPPPPPK..",
            ".KPPPPPPPPPPDK..",
            ".KDPPPPPPPPDDK..",
            "..KDDDKKDDDDK...",
            "...KKK..KKKK....",
        ],
        palette: { K: "black", P: main("base", "#E8433A"), L: main("light", "#FF9C94"), D: main("dark", "#A82620"), S: accent("base", "#5DC44A") },
    },
    {
        id: 10038,
        name: "LIGHTBULB",
        staff_only: false,
        // the bulb follows the main colour, the rays the accent
        grid: [
            ".....KKKKKK.....",
            ".S..KWWLLLLK..S.",
            "...KWLLPPPPPK...",
            "...KLPPPPPPPK...",
            "SS.KLPPPPPPPK.SS",
            "...KPPPPPPPDK...",
            "...KPPKPPKPDK...",
            ".S..KPPKKPDK..S.",
            "....KPPKKPDK....",
            ".....KPKKPK.....",
            ".....KGGGGK.....",
            ".....KggggK.....",
            ".....KGGGGK.....",
            "......KggK......",
            ".......KK.......",
            "................",
        ],
        palette: {
            K: "black",
            W: "white",
            G: "#B8BDC9",
            g: "#7D8494",
            P: main("base", "#FFD23F"),
            L: main("light", "#FFF3A8"),
            D: main("dark", "#D9A21A"),
            S: accent("base", "#FF9F1C"),
        },
    },
    {
        id: 10039,
        name: "KEY",
        staff_only: false,
        // a key in the main colour
        grid: [
            "..KKKK..........",
            ".KLLLPK.........",
            "KLLKKPPK........",
            "KLK..KPK........",
            "KLK..KPK........",
            "KPPKKPPK........",
            ".KPPPPDLK.......",
            "..KKKKDPLK......",
            "......KDPLK.....",
            ".......KDPLK....",
            ".......KKDPLK...",
            ".......KPPDPLK..",
            ".......KDDKDPLK.",
            "........KKPPDPK.",
            ".........KDDKKK.",
            "..........KK....",
        ],
        palette: { K: "black", P: main("base", "#FFC83D"), L: main("light", "#FFEFA8"), D: main("dark", "#C98F12") },
    },
    {
        id: 10040,
        name: "CHERRIES",
        staff_only: false,
        // the cherries follow the main colour, the leaf the accent
        grid: [
            "...........KK...",
            "..........KSSK..",
            ".........BSSK...",
            "........B.B.....",
            ".......B..B.....",
            "......B....B....",
            ".....B.....B....",
            "....B.......B...",
            "..KKKK....KKKK..",
            ".KLLPPK..KLLPPK.",
            "KLPPPPPKKLPPPPPK",
            "KPPPPPPKKPPPPPPK",
            "KPPPPPDKKPPPPPDK",
            ".KPPPDK..KPPPDK.",
            "..KKKK....KKKK..",
            "................",
        ],
        palette: { K: "black", B: "#6B4A30", P: main("base", "#E8233A"), L: main("light", "#FF8F99"), D: main("dark", "#A3101F"), S: accent("base", "#3FA34D") },
    },
    {
        id: 10041,
        name: "SLIME",
        staff_only: false,
        // a slime: the body follows the main colour, the blush the accent
        grid: [
            "................",
            "......KKKK......",
            "....KKLLLPKK....",
            "...KLWLPPPPPK...",
            "..KLWLPPPPPPPK..",
            "..KLLPPPPPPPPK..",
            ".KPPPPPPPPPPPPK.",
            ".KPPKWPPPPKWPPK.",
            ".KPPKKPPPPKKPPK.",
            "KPPSPPPPPPPPSPPK",
            "KPPPPPKPPKPPPPDK",
            "KPPPPPPKKPPPPPDK",
            "KDPPPPPPPPPPPPDK",
            "KDDDPPPPPPPPDDDK",
            ".KKDDDDDDDDDDKK.",
            "...KKKKKKKKKK...",
        ],
        palette: { K: "black", W: "white", P: main("base", "#5DDC6A"), L: main("light", "#B5F5BC"), D: main("dark", "#2F9E3C"), S: accent("light", "#FF8FB0") },
    },
    {
        id: 10042,
        name: "BATTERY",
        staff_only: false,
        // the casing follows the main colour, the charge the accent
        grid: [
            "................",
            "................",
            "................",
            ".KKKKKKKKKKKK...",
            "KLLLLLLLLLLLPK..",
            "KLBBBBBBBBBBPK..",
            "KLBAABAABAABPKK.",
            "KLBSSBSSBSSBPKPK",
            "KLBSSBSSBSSBPKPK",
            "KLBTTBTTBTTBPKK.",
            "KLBBBBBBBBBBPK..",
            "KPPPPPPPPPPPDK..",
            ".KKKKKKKKKKKK...",
            "................",
            "................",
            "................",
        ],
        palette: {
            K: "black",
            B: "#2A2D35",
            P: main("base", "#B8BDC9"),
            L: main("light", "#E9ECF2"),
            D: main("dark", "#7D8494"),
            S: accent("base", "#43E06B"),
            A: accent("light", "#A8F5BA"),
            T: accent("dark", "#1F9E44"),
        },
    },
    {
        id: 10043,
        name: "CHATGPT",
        staff_only: false,
        // the knot on its app tile: the tile follows the main colour
        grid: [
            "..KKKKKKKKKKKK..",
            ".KPPPPPPPPPPPPK.",
            "KPPPPPPPPPPPPPPK",
            "KPPPPPWWWWPPPPPK",
            "KPPPWWWPPWWWPPPK",
            "KPPPWPPWWPPWPPPK",
            "KPPWWPWPPWPWWPPK",
            "KPPWPWPPPPWPWPPK",
            "KPPWPWPPPPWPWPPK",
            "KPPWWPWPPWPWWPPK",
            "KPPPWPPWWPPWPPPK",
            "KPPPWWWPPWWWPPPK",
            "KPPPPPWWWWPPPPPK",
            "KPPPPPPPPPPPPPPK",
            ".KPPPPPPPPPPPPK.",
            "..KKKKKKKKKKKK..",
        ],
        palette: { K: "black", W: "white", P: main("base", "#10A37F") },
    },
    {
        id: 10044,
        name: "GROK",
        staff_only: false,
        // the broken ring and slash on a dark tile, which follows the main colour
        grid: [
            "..KKKKKKKKKKKK..",
            ".KPPPPPPPPPPPPK.",
            "KPPPPPPPPPPPPPPK",
            "KPPPPPPWWPPPWPPK",
            "KPPPPWWWWPPWPPPK",
            "KPPPWWPPPPWPPPPK",
            "KPPPWPPPPWPPPPPK",
            "KPPWWPPPWPPWWPPK",
            "KPPWWPPWPPPWWPPK",
            "KPPPPPWPPPPWPPPK",
            "KPPPPWPPPPWWPPPK",
            "KPPPWPPWWWWPPPPK",
            "KPPWPPPWWPPPPPPK",
            "KPPPPPPPPPPPPPPK",
            ".KPPPPPPPPPPPPK.",
            "..KKKKKKKKKKKK..",
        ],
        palette: { K: "black", W: "white", P: main("dark", "#16181D") },
    },
    {
        id: 10045,
        name: "CLAUDE",
        staff_only: false,
        // the starburst in the main colour, with no outline so the gaps between its rays show through
        grid: [
            "................",
            "................",
            ".......P........",
            ".......P..P.....",
            "....P..P.PP.....",
            "....PP.P.P..PP..",
            ".....PPPPPPPP...",
            ".PPPPPPPPPPP....",
            "....PPPPPPPPPP..",
            "....PPPPPPPPPP..",
            "..PPPPPPPPPP....",
            ".....PPPPPPPP...",
            "....PP.P.P......",
            "...PP..P.PP.....",
            "...P...P..P.....",
            "................",
        ],
        palette: { P: main("base", "#D97757") },
    },
    {
        id: 10046,
        name: "DEEPSEEK",
        staff_only: false,
        // the whale in the main colour
        grid: [
            "................",
            "................",
            "..........KK..K.",
            ".........KPPKKPK",
            "..........KPPPK.",
            "...........KPK..",
            "....KKKKK..KPK..",
            "..KKPPPPPKKKPK..",
            ".KPPPPPPPPPPPK..",
            "KPPWKPPPPPPPPK..",
            "KPPKKPPPPPPPK...",
            "KLLLPPPPPPPDK...",
            ".KLLLLLLLDDK....",
            "..KKKKKKKKK.....",
            "................",
            "................",
        ],
        palette: { K: "black", W: "white", P: main("base", "#4D6BFE"), L: main("light", "#AEBBFF"), D: main("dark", "#2F47C9") },
    },
    {
        id: 10047,
        name: "CHICKEN",
        staff_only: false,
        pack: "SizzRime's Chicken",
        // a chicken: the feathers follow the main colour, the comb and wattle the accent
        grid: [
            "................",
            "....K.K.........",
            "...KSKSK........",
            "...KSSSK........",
            "..KLLPPPK.......",
            ".KLPKPPPK...KK..",
            "KOOPPPPPK..KLPK.",
            ".KKSPPPPPKKLPPK.",
            "..KSLPPPPPPPPPK.",
            "..KLPPPPPPPPPPK.",
            "..KPPPPDDDPPPDK.",
            "...KPPPPDDPPPDK.",
            "....KPPPPPPPDK..",
            ".....KKKKKKKK...",
            "......KOK.KOK...",
            ".....KOOK.KOOK..",
        ],
        palette: { K: "black", O: "#FF9F1C", P: main("base", "#F5F3EC"), L: main("light", "#FFFFFF"), D: main("dark", "#BFC3CC"), S: accent("base", "#E8333A") },
    },
    {
        id: 10048,
        name: "DISCORD",
        staff_only: false,
        pack: "The worst company ever",
        // the logo, traced from its outline at badge size, in the main colour
        grid: [
            "................",
            "................",
            "...KKKKKKKKKK...",
            "..KLLLLLPPPPDK..",
            ".KLPPPPPPPPPPDK.",
            ".KLPPPPPPPPPPDK.",
            ".KLPPPPPPPPPPDK.",
            "KLPPPWWPPWWPPPDK",
            "KLPPPWWPPWWPPPDK",
            "KLPPPWWPPWWPPPDK",
            "KLPPPPPPPPPPPPDK",
            "KLPPPPPPPPPPPPDK",
            ".KLPPKKKKKKPPDK.",
            "..KKK......KKK..",
            "................",
            "................",
        ],
        palette: { K: "black", W: "white", P: main("base", "#5865F2"), L: main("light", "#A3ABFF"), D: main("dark", "#3C45B8") },
    },
];

// how many of the server's badge colours a badge uses, which the client uses to decide whether to offer the accent colour
export const clanBadgeColorCount = (badge: CustomClanBadge) => {
    const shades = Object.values(badge.palette).filter((fill): fill is ClanBadgeShade => typeof fill === "object");
    return shades.some((shade) => shade.ch === "S") ? 2 : 1;
};

export const customClanBadge = (id: number | string | null | undefined) => CUSTOM_CLAN_BADGES.find((badge) => badge.id === Number(id));

// the pack a badge is listed under
export const clanBadgePack = (badge: CustomClanBadge) => badge.pack ?? CUSTOM_CLAN_BADGE_PACK;

export const isStaffOnlyClanBadge = (id: number | string | null | undefined) => !!customClanBadge(id)?.staff_only;
